import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';
import { saveAs } from 'file-saver';
import { jsPDF } from 'jspdf';
import type { DeckAnalysis } from '@/types/database';

// Helper: normalize a field that can be string or string[]
function toArray(value: unknown): string[] {
    if (Array.isArray(value)) return value;
    if (typeof value === 'string' && value) return [value];
    return [];
}

function toString(value: unknown): string {
    if (Array.isArray(value)) return value.join('\n• ');
    if (typeof value === 'string') return value;
    return '';
}

interface ReportData {
    companyName: string;
    analysis: DeckAnalysis;
}

// ─── DOCX Export ──────────────────────────────────

export async function downloadAsDocx({ companyName, analysis }: ReportData) {
    const sections: { title: string; content: unknown }[] = [
        { title: 'Executive Summary', content: analysis.summary },
        { title: 'Problem Analysis', content: analysis.problem },
        { title: 'Solution & Product', content: analysis.solution },
        { title: 'Market Opportunity', content: analysis.market },
        { title: 'Business Model & Unit Economics', content: analysis.businessModel },
        { title: 'Traction & Metrics', content: analysis.traction },
        { title: 'Team Assessment', content: analysis.team },
        { title: 'Competitive Landscape', content: analysis.competitiveLandscape },
        { title: 'Financial Projections', content: analysis.financialProjection },
        { title: 'Investment Thesis', content: analysis.investmentThesis },
        { title: 'Strengths', content: analysis.strengths },
        { title: 'Risks', content: analysis.risks },
        { title: 'Red Flags', content: analysis.redFlags },
        { title: 'Due Diligence Questions', content: analysis.dueDiligenceQuestions || analysis.suggestedQuestions },
    ];

    const children: Paragraph[] = [];

    // Title
    children.push(new Paragraph({
        children: [new TextRun({ text: `Investment Analysis Report`, bold: true, size: 36, font: 'Calibri' })],
        heading: HeadingLevel.TITLE,
        alignment: AlignmentType.CENTER,
        spacing: { after: 100 },
    }));
    children.push(new Paragraph({
        children: [new TextRun({ text: companyName, bold: true, size: 28, font: 'Calibri', color: '6366f1' })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
    }));

    // Separator
    children.push(new Paragraph({
        border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'cccccc' } },
        spacing: { after: 200 },
    }));

    // Verdict & confidence
    if (analysis.verdict) {
        children.push(new Paragraph({
            children: [
                new TextRun({ text: 'Verdict: ', bold: true, size: 24, font: 'Calibri' }),
                new TextRun({ text: analysis.verdict, size: 24, font: 'Calibri', color: analysis.verdict.startsWith('INVEST') ? '16a34a' : analysis.verdict.startsWith('PASS') ? 'ef4444' : 'f59e0b' }),
            ],
            spacing: { after: 100 },
        }));
    }
    if (analysis.confidenceScore !== undefined) {
        children.push(new Paragraph({
            children: [
                new TextRun({ text: 'Confidence Score: ', bold: true, size: 22, font: 'Calibri' }),
                new TextRun({ text: `${analysis.confidenceScore}%`, size: 22, font: 'Calibri' }),
            ],
            spacing: { after: 300 },
        }));
    }

    // Sections
    for (const section of sections) {
        if (!section.content || (Array.isArray(section.content) && section.content.length === 0)) continue;

        children.push(new Paragraph({
            children: [new TextRun({ text: section.title, bold: true, size: 26, font: 'Calibri', color: '6366f1' })],
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 300, after: 100 },
        }));

        const items = toArray(section.content);
        if (items.length > 0 && Array.isArray(section.content)) {
            for (const item of items) {
                children.push(new Paragraph({
                    children: [new TextRun({ text: item, size: 21, font: 'Calibri' })],
                    bullet: { level: 0 },
                    spacing: { after: 60 },
                }));
            }
        } else {
            children.push(new Paragraph({
                children: [new TextRun({ text: toString(section.content), size: 21, font: 'Calibri' })],
                spacing: { after: 100 },
            }));
        }
    }

    // Footer
    children.push(new Paragraph({
        border: { top: { style: BorderStyle.SINGLE, size: 1, color: 'cccccc' } },
        spacing: { before: 400 },
    }));
    children.push(new Paragraph({
        children: [new TextRun({ text: `Generated by Dholakia Ventures Deal Flow Platform — ${new Date().toLocaleDateString('en-IN')}`, size: 18, font: 'Calibri', color: '999999', italics: true })],
        alignment: AlignmentType.CENTER,
        spacing: { before: 100 },
    }));

    const doc = new Document({
        sections: [{ children }],
    });

    const blob = await Packer.toBlob(doc);
    saveAs(blob, `${companyName.replace(/[^a-zA-Z0-9 ]/g, '')} - Analysis Report.docx`);
}

// ─── PDF Export ──────────────────────────────────

export function downloadAsPdf({ companyName, analysis }: ReportData) {
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = 20;

    const checkPageBreak = (needed: number) => {
        if (y + needed > pdf.internal.pageSize.getHeight() - 20) {
            pdf.addPage();
            y = 20;
        }
    };

    // Title
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(20);
    pdf.setTextColor(99, 102, 241);
    pdf.text('Investment Analysis Report', pageWidth / 2, y, { align: 'center' });
    y += 10;

    pdf.setFontSize(16);
    pdf.text(companyName, pageWidth / 2, y, { align: 'center' });
    y += 8;

    // Separator line
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Verdict
    if (analysis.verdict) {
        pdf.setFontSize(12);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(0, 0, 0);
        pdf.text('Verdict: ', margin, y);
        const verdictX = margin + pdf.getTextWidth('Verdict: ');
        if (analysis.verdict.startsWith('INVEST')) pdf.setTextColor(22, 163, 74);
        else if (analysis.verdict.startsWith('PASS')) pdf.setTextColor(239, 68, 68);
        else pdf.setTextColor(245, 158, 11);
        pdf.setFont('helvetica', 'normal');
        const verdictLines = pdf.splitTextToSize(analysis.verdict, contentWidth - pdf.getTextWidth('Verdict: '));
        pdf.text(verdictLines, verdictX, y);
        y += verdictLines.length * 5 + 3;
    }

    if (analysis.confidenceScore !== undefined) {
        pdf.setTextColor(0, 0, 0);
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(11);
        pdf.text(`Confidence Score: ${analysis.confidenceScore}%`, margin, y);
        y += 10;
    }

    const sections: { title: string; content: unknown }[] = [
        { title: 'Executive Summary', content: analysis.summary },
        { title: 'Problem Analysis', content: analysis.problem },
        { title: 'Solution & Product', content: analysis.solution },
        { title: 'Market Opportunity', content: analysis.market },
        { title: 'Business Model & Unit Economics', content: analysis.businessModel },
        { title: 'Traction & Metrics', content: analysis.traction },
        { title: 'Team Assessment', content: analysis.team },
        { title: 'Competitive Landscape', content: analysis.competitiveLandscape },
        { title: 'Financial Projections', content: analysis.financialProjection },
        { title: 'Investment Thesis', content: analysis.investmentThesis },
        { title: 'Strengths', content: analysis.strengths },
        { title: 'Risks', content: analysis.risks },
        { title: 'Red Flags', content: analysis.redFlags },
        { title: 'Due Diligence Questions', content: analysis.dueDiligenceQuestions || analysis.suggestedQuestions },
    ];

    for (const section of sections) {
        if (!section.content || (Array.isArray(section.content) && section.content.length === 0)) continue;

        checkPageBreak(20);

        // Section title
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(13);
        pdf.setTextColor(99, 102, 241);
        pdf.text(section.title, margin, y);
        y += 2;

        // Underline
        pdf.setDrawColor(99, 102, 241);
        pdf.setLineWidth(0.5);
        pdf.line(margin, y, margin + pdf.getTextWidth(section.title), y);
        y += 6;

        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(10);
        pdf.setTextColor(50, 50, 50);

        const items = toArray(section.content);
        if (items.length > 0 && Array.isArray(section.content)) {
            for (const item of items) {
                checkPageBreak(10);
                const bulletText = `•  ${item}`;
                const lines = pdf.splitTextToSize(bulletText, contentWidth - 4);
                pdf.text(lines, margin + 2, y);
                y += lines.length * 4.5 + 2;
            }
        } else {
            const text = toString(section.content);
            const lines = pdf.splitTextToSize(text, contentWidth);
            checkPageBreak(lines.length * 4.5);
            pdf.text(lines, margin, y);
            y += lines.length * 4.5 + 2;
        }

        y += 4;
    }

    // Footer
    checkPageBreak(15);
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 6;
    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Generated by Dholakia Ventures Deal Flow Platform — ${new Date().toLocaleDateString('en-IN')}`, pageWidth / 2, y, { align: 'center' });

    pdf.save(`${companyName.replace(/[^a-zA-Z0-9 ]/g, '')} - Analysis Report.pdf`);
}
